services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"

  selenide-test:
    build:
      context: .
      dockerfile: Dockerfile.selenoid-test
    container_name: selenoid-test
    depends_on:
      - selenoid
    networks:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub              # <--- you can use this in your Java code
    volumes:
      - ~/.m2:/root/.m2
networks:
  selenoid: